macro- ; 
macro*10 25000 ; 
macro[ 3000 ; 
macro=; 
if ( ntax < 3 ) errmsg Must read dataset before running this script! ; end 
var: widval thick gc SVG fnama[30] fnamb[30] fsav[30] blens[(2*ntax)] vals[(2*ntax)] ; 
if ( argnumber < 3 ) 
errmsg 
-----------------------------------------------------------------------------------
This script takes the trees from a file (first arg, presumably optimal trees),
calculates the strict consensus and its branch lengths (optimizing the characters
onto the consensus., lengths reported are minimum lengths). Then takes the trees
from a second file (second arg, presumably trees from bootstrapping or, more
generally, resampling) and calculates the frequencies (optionally, frequency 
differences, GC) of the groups in the strict consensus among the trees contained
in the second file. 

The idea of the script is to include support values on a tree where the branch 
lengths are shown graphically, circumventing the need for typing a series of 
commands in TNT itself. The results can be saved as a Newick/Nexus tree, or 
directly as an SVG file. See below for arguments. 

-----------------------------------------------------------------------------------
A script written for Julian Faivovich, hence the name. According to the dictionary 
of Argentinian slang, 

     forfai - (pop.) Sin dinero, indigente// exhausto// individuo al margen de un 
     negocio determinado (C. y P.), excluido// (turf) Caballo retirado antes de 
     correrse la carrera en la que estaba anotado.

-----------------------------------------------------------------------------------
Three args are mandatory: 

  1 - file with optimal trees., TNT will do the strict consensus of these., 
  2 - file with resampled trees., TNT will map freq (default) or gc onto the 
      tree produced by step 1., 
  3 - file where the tree diagram should be saved (in Newick, default, or
      as an SVG diagram, with SVG as argument beyond the first three.

After the file names, you can use: 
      
   SVG          save tree as SVG, instead of Newick 
   thick N      make tree branches thicker in SVG diagrams 
   GC           display GC values instead of frequencies 
   wid          width factor for SVG diagrams (1 = given size)

Note that this script *must* be placed in a directory whose path 
does *not* have any blank spaces!
-----------------------------------------------------------------------------------

; 
end    
goto =%0 ; 
goto getargs %1 %2 %3 %4 %5 %6 %7 %8 %9 ; 
keep 0 ; 
hold 3000 / 10 ; 
p $fnama ; 
nelsen * ; tchoose/; 
maketable + blens ; 
blen 0 ; 
maketable - ; 
set * blens /= ( nchar + 1 ) ; 
collapse notemp ; 
p $fnamb ; 
if ( 'gc' ) 
     set vals freqdlist [ 0 ] 1. ; 
else set vals freqlist [ 0 ] 1. ; end 
collapse temp ; 
/** Now, compose labels ****/
ttag - ; 
ttag * 0 ; 
if ( 'SVG' ) 
  set * blens *= ( 100 * 'widval' ) ; 
  loop 0 ntax 
    ttag +#1 (0,0,0,'thick':'blens[#1]');
    stop
  loop (root+1) nnodes[0] 
    ttag +#1 (0,0,0,'thick':'blens[#1]')/'/.0vals[#1]';
    stop
  ttag & $fsav color legup 6 bfontsize 10 italics ; 
else 
  taxname=; 
  loop 0 ntax 
    ttag +#1 :'blens[#1]';
    stop
  loop (root+1) nnodes[0] 
    ttag +#1 '/.0vals[#1]':'blens[#1]';
    stop
  export < $fsav ; 
  end 
quote LISTO!! ;   
proc/; 

label getargs ; 
var: i j ; 
set gc 0 ; 
set thick 3 ; 
set SVG 0 ; 
set fnama $%1 ; 
set fnamb $%2 ; 
set fsav $%3 ; 
set widval 1 ; 
loop 4+1 argnumber 
   set i #1 ; 
   if ( eqstring[ %('i') SVG ] ) set SVG 1 ; continue ; end 
   if ( eqstring[ %('i') GC ] ) set gc 1 ; continue ; end 
   if ( eqstring[ %('i') thick ] ) 
      set j 'i' + 1 ; 
      if ( 'j' > argnumber ) errmsg A value must follow thick ; end 
      set thick %('j') ; 
      set j ++ ; 
      setloop 'j' ; 
      end 
   if ( eqstring[ %('i') wid ] ) 
      set j 'i' + 1 ; 
      if ( 'j' > argnumber ) errmsg A value must follow wid ; end 
      set widval %('j') ; 
      set j ++ ; 
      setloop 'j' ; 
      end 
   errmsg Unknown argument: %('i'); 
   stop 
proc/; 

