log score_MP_MOLvsTE_results.txt

macro=;

/* MOL partition on MOL tree */
proc ../../Other/ALL_DATA/001/tnt/001_MOL_data.tnt ;
nstates nogaps;
hold 10000;
proc ../../Other/ALL_DATA/001/tnt/001a_trees_MOL_TNT_results.nwk;
best;
tchoose /;
chomo;
proc Stats.run;
/* TE partition on TE tree */
proc ../../Other/ALL_DATA/001/tnt/001_TE_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/001/tnt/001c_trees_TE_TNT_results.nwk;
best;
tchoose /;
chomo;
proc Stats.run;
/* MOL partition on TE tree */
proc ../../Other/ALL_DATA/001/tnt/001_MOL_data.tnt ;
nstates nogaps;
hold 10000;
proc ../../Other/ALL_DATA/001/tnt/001c_trees_TE_TNT_results.nwk;
best;
tchoose /;
chomo;
proc Stats.run;
/* MORPH partition on TE tree */
proc ../../Other/ALL_DATA/001/tnt/001_MORPH_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/001/tnt/001c_trees_TE_TNT_results.nwk;
best;
tchoose /;
chomo;
proc Stats.run;

/* MOL partition on MOL tree */
proc ../../Other/ALL_DATA/002/tnt/002_MOL_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/002/tnt/002a_MOL_TNT_results.out;
best;
tchoose /;
chomo;
proc Stats.run;
/* TE partition on TE tree */
proc ../../Other/ALL_DATA/002/tnt/002_TE_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/002/tnt/002c_TE_TNT_results.out;
best;
tchoose /;
chomo;
proc Stats.run;
/* MOL partition on TE tree */
proc ../../Other/ALL_DATA/002/tnt/002_MOL_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/002/tnt/002c_TE_TNT_results.out;
best;
chomo;
proc Stats.run;
/* MORPH partition 1 on TE tree */
proc ../../Other/ALL_DATA/002/tnt/002_MORPH_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/002/tnt/002c_TE_TNT_results.out;
best;
tchoose /;
chomo;
proc Stats.run;
/* MORPH partition 2 on TE tree */
proc ../../Other/ALL_DATA/002/tnt/002_MORPH2_data.tnt ;
hold 10000;
proc ../../Other/ALL_DATA/002/tnt/002c_TE_TNT_results.out;
best;
tchoose /;
chomo;
proc Stats.run;

log /;
quit;
